[platformio]
default_envs = pro-mini-5v-16mhz

[env:pro-mini-5v-16mhz]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 9600
extra_scripts = pre:tools/load_env.py
build_flags =
  -Wall
  -Wextra
